### ISSUE TITLE
Monster/combat tool displays stats for wrong monster

### ISSUE THREAD

**Issue by evanfields** [sdoddler/D-D-Software-Suite#1]
Double click on a monster in the main list of monsters, and sometimes the popup contains info for the wrong monster. Example below:
![wrongmonster](https://cloud.githubusercontent.com/assets/10092265/17708520/6dfe27b8-63b3-11e6-8d34-a550fdcf059b.PNG)

**Comment by sdoddler** [comment]
Have fixed this, will just have to wait till i'm home to upload changes.

**Comment by sdoddler** [comment]
Have uploaded updated .au3 and .exe which should resolve the issue.
