### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by evanfields** [sdoddler/D-D-Software-Suite#2]
Windows Defender detected a trojan in the monster and combat tool...

<img width="639" alt="trojan" src="https://cloud.githubusercontent.com/assets/10092265/18249391/eb9ba4c8-734b-11e6-8c5c-ee256dfd2a4b.PNG">

Edit: @sdoddler thanks for the response. I should clarify (hopefully it was obvious the first time!) that I opened the issue not as "this is a virus" but "this looks like a false positive."

**Comment by sdoddler** [comment]
I've written everything that is not part of the Base\UDFs of AutoIT - There are no viruses inside the program. Only 6/54 test positive on [virus total](https://www.virustotal.com/en/file/0ab80e62047a706ced145c0885c566b175fab233e7d3f776267cff7c0a1a8a38/analysis/1473115305/). This is a common problem with AutoIT as the language can be used for the wrong purposes & compiles as a standalone exe
